#!/bin/bash
FILE=Memoria
make $FILE
if test -f "./$FILE"; then
    valgrind --tool=memcheck --leak-check=full --show-possibly-lost=no --show-reachable=no --show-leak-kinds=all --num-callers=20 ./$FILE Memoria.cfg
fi